version: '3'

services:
    proxy:
        image: nginx
        volumes:
          - "$PWD/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
          - "$PWD/etc/nginx/conf.d/isucon-app.conf:/etc/nginx/conf.d/default.conf"
          - "$PWD/webapp/static:/opt/webapp/static"
        ports:
          - "80:80"
        depends_on:
          - db
          - app

    app:
        build:
            context: .
            dockerfile: ./webapp/go/Dockerfile
        command: "make -C webapp/go build run/docker"
        environment:
          GO_PORT: ":8081"
          GO_INIT: "../../db/init-docker.sh"
        volumes:
          - "$PWD/db:/opt/isucon/db"
          - "$PWD/webapp:/opt/isucon/webapp"
        
    db:
        image: mariadb:5.5
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_PASSWORD: ""
            MYSQL_DATABASE: "torb"
            MYSQL_USER: "isucon"
            MYSQL_PASSWORD: "isucon"
        ports:
            - "33060:3306"
        volumes:
          - "$PWD/db/001_run-for-docker.sh:/docker-entrypoint-initdb.d/001_run-for-docker.sh"
          - "$PWD/db/init-user.sh:/opt/migration/init-user.sh"
          - "$PWD/etc/my.docker.cnf:/etc/mysql/conf.d/my.cnf"
          - "$PWD/etc/my.cnf.d:/etc/my.cnf.d"

    bench:
        build:
            context: .
            dockerfile: ./webapp/go/Dockerfile
        command: "make build-osx"
        volumes:
          - "$PWD/bench:/opt/isucon/"
